class Linux:
    get_all_details="uname -a"
    get_kernal_name = "uname -s"
    get_node_name = "uname -n"
    get_kernal_release = "uname -r"
    get_kernal_version = "uname -v"
    get_machine = "uname -m"
    get_processor = "uname -p"
    get_hardware = "uname -i"
    get_operating_system = "uname -o"
    make_dir = "mkdir -p "
    ping = "ping "
    ping_complete = " -w 5 | grep rtt"
    lsb_release = "lsb_release -a"
    moveToDirectory = "cd "


    class Ubuntu:
        apt_update= "apt-get update"
        install_git= "apt-get install git"
        check_git = "git --version"
        check_node = "node -v"
        check_python = "python3 --version"
        check_freeport = " hash freeport"
        install_npm = "sudo apt-get -y install npm"
        install_nvmfromnpm = "npm install nvm"
        install_nodefromnpm = "npm install node"
        install_pm2fromnpm = "npm install pm2 -g"
        install_node_legacy = "sudo apt-get -y install nodejs-legacy"
        install_node_js = "sudo apt-get -y install nodejs"
        install_node = "sudo apt-get -y install node"
        run_nodejsappplication = "node "
        run_nodejsappplication_pm2 = "pm2 start -f "
        stop_nodejsappplication_pm2 = "pm2 stop "
        delete_nodejsappplication_pm2 = "pm2 delete "
        show_nodejsappplication_pm2 = "pm2 show "
        pm2_name = " --name "
        npm_install = "npm install"

        class PythonDependencies :
            install_python2 = ""
            install_python3 = ""
            install_python2_dev_tools = "sudo apt-get install python-dev"
            install_python3_dev_tools = "sudo apt-get install python3-dev "
            install_python3_setup_tools = "sudo apt-get install python3-setuptools"
            install_python2_setup_tools = "sudo apt-get install python-setuptools"
            freeportinstall  = "pip install freeport"

